### ISSUE TITLE
image

### ISSUE THREAD

**Issue by mjung1798** [jmini1234/tripmate#36]

**Comment by mjung1798** [comment]
![image](https://user-images.githubusercontent.com/26458200/50136900-b4bf3000-02dc-11e9-8a24-fa52b8ff37be.png)

**Comment by jmini1234** [comment]
[1545113781846](C:\Users\심정민\AppData\Roaming\Typora\typora-user-images\1545113781846.png)

**Comment by jmini1234** [comment]
![image](https://user-images.githubusercontent.com/37237145/50137223-e1277c00-02dd-11e9-8bbe-07a73202cab1.png)

![image](https://user-images.githubusercontent.com/37237145/50137304-251a8100-02de-11e9-8a58-0d6bab21119c.png)

**Comment by jmini1234** [comment]
![image](https://user-images.githubusercontent.com/37237145/50137339-3a8fab00-02de-11e9-9896-33e291d18f31.png)

![image](https://user-images.githubusercontent.com/37237145/50137369-4aa78a80-02de-11e9-9c05-8c8e9017f5f8.png)

**Comment by jmini1234** [comment]
![image](https://user-images.githubusercontent.com/37237145/50137397-5b580080-02de-11e9-8d79-084b0ec10fd7.png)

![image](https://user-images.githubusercontent.com/37237145/50137418-6f036700-02de-11e9-8bce-1d5be57bffae.png)

**Comment by jmini1234** [comment]
![image](https://user-images.githubusercontent.com/37237145/50137869-e4bc0280-02df-11e9-86ac-c56c5010562b.png)

![image](https://user-images.githubusercontent.com/37237145/50137942-277dda80-02e0-11e9-8d7d-45eaf2b15497.png)

**Comment by jmini1234** [comment]
![image](https://user-images.githubusercontent.com/37237145/50138024-73308400-02e0-11e9-86eb-adbf3abe6a69.png)

![image](https://user-images.githubusercontent.com/37237145/50138104-b3900200-02e0-11e9-911c-db145a71905a.png)
![image](https://user-images.githubusercontent.com/37237145/50138145-df12ec80-02e0-11e9-8515-ee9157b29b59.png)

**Comment by jmini1234** [comment]
![image](https://user-images.githubusercontent.com/37237145/50139279-90675180-02e4-11e9-8003-f26c080711a2.png)

![image](https://user-images.githubusercontent.com/37237145/50139322-b260d400-02e4-11e9-8bdf-a53ffb67c30c.png)

**Comment by jmini1234** [comment]
![image](https://user-images.githubusercontent.com/37237145/50140381-e689c400-02e7-11e9-8404-57d05d295125.png)

**Comment by jmini1234** [comment]
![image](https://user-images.githubusercontent.com/37237145/50142446-872eb280-02ed-11e9-970a-1485ba27fcad.png)

**Comment by jmini1234** [comment]
<img width="788" alt="git_flow" src="https://user-images.githubusercontent.com/37237145/50142476-a2012700-02ed-11e9-86c3-c6383abf948e.png">

**Comment by mjung1798** [comment]
![image](https://user-images.githubusercontent.com/26458200/50151311-e4356300-0303-11e9-80ff-36f5f3567e3c.png)

**Comment by mjung1798** [comment]
![image](https://user-images.githubusercontent.com/26458200/50152194-53ac5200-0306-11e9-9f3a-8b1e48fb7088.png)
